"use strict";

module.exports = {
  REGISTER: "REGISTER",
  GENERAL_PURPOSE_REGISTER: "GENERAL_PURPOSE_REGISTER",
  SEGMENT_REGISTER: "SEGMENT_REGISTER",
  SPECIAL_PURPOSE_REGISTER: "SPECIAL_PURPOSE_REGISTER",
  MEMORY: "MEMORY",
  IMMEDIATE: "IMMEDIATE"
};